export const PORTALS = [
  { name: "MoPSW", url: "ports.gov.in", purpose: "Policy, circulars, port statistics" },
  { name: "Sagarmala Dashboard", url: "sagarmala.gov.in", purpose: "Project tracking, scheme alignment" },
  { name: "CPPP (e-Tendering)", url: "eprocure.gov.in", purpose: "Central government bid submission" },
  { name: "GeM Portal", url: "gem.gov.in", purpose: "Government e-marketplace procurement" },
  { name: "ICEGATE", url: "icegate.gov.in", purpose: "Customs filing, bill of entry tracking" },
  { name: "DigiSky", url: "digitalsky.dgca.gov.in", purpose: "Drone flight approvals" },
  { name: "MCA21", url: "mca.gov.in", purpose: "Company verification, director details" },
  { name: "DG Shipping", url: "dgshipping.gov.in", purpose: "Seafarer certificates, vessel registry" },
];

export const LEGISLATION = [
  { name: "Major Port Authorities Act", year: "2021", note: "Governance, contracting authority, land management" },
  { name: "Indian Ports Act", year: "1908 (amended)", note: "Minor ports, port jurisdiction, safety" },
  { name: "ISPS Code (SOLAS)", year: "International", note: "Port security and access protocols" },
  { name: "Merchant Shipping Act", year: "1958 (amended)", note: "Vessel regulation, DG Shipping authority" },
  { name: "Customs Act", year: "1962 (amended)", note: "EXIM operations, customs procedures" },
  { name: "CRZ Notification", year: "2019", note: "Coastal construction, environmental compliance" },
  { name: "General Financial Rules", year: "2017", note: "Procurement norms for government bodies" },
  { name: "Prevention of Corruption Act", year: "1988 (amended 2018)", note: "Anti-bribery compliance for government engagement" },
];

export const GLOSSARY = [
  ["MoPSW", "Ministry of Ports, Shipping and Waterways"],
  ["MPA", "Major Port Authority (post-2021 Act)"],
  ["GMB", "Gujarat Maritime Board"],
  ["DG Shipping", "Directorate General of Shipping"],
  ["TAMP", "Tariff Authority for Major Ports"],
  ["ISPS", "International Ship and Port Facility Security Code"],
  ["HEP", "Harbour Entry Pass"],
  ["PSO", "Port Security Officer"],
  ["TOS", "Terminal Operating System"],
  ["PCS", "Port Community System"],
  ["CRZ", "Coastal Regulation Zone"],
  ["GFR", "General Financial Rules"],
  ["QCBS", "Quality and Cost Based Selection"],
  ["EoI", "Expression of Interest"],
  ["RFP", "Request for Proposal"],
  ["DPR", "Detailed Project Report"],
  ["PMC", "Project Management Consultancy"],
  ["S2I2", "Sagarmala Startup Innovation Initiative"],
  ["MIF", "Maritime India Foundation"],
  ["MIH", "Maritime Innovation Hub"],
  ["PPP", "Public Private Partnership"],
  ["GeM", "Government e-Marketplace"],
  ["CPPP", "Central Public Procurement Portal"],
  ["CHA", "Custom House Agent"],
  ["LNG", "Liquefied Natural Gas"],
  ["MMT", "Million Metric Tonnes"],
  ["IRS", "Indian Register of Shipping"],
  ["DIN", "Document Identification Number"],
  ["CVC", "Central Vigilance Commission"],
  ["IEM", "Independent External Monitor"],
  ["ICEGATE", "Indian Customs Electronic Gateway"],
  ["FTWZ", "Free Trade Warehousing Zone"],
  ["AEO", "Authorised Economic Operator"],
  ["MMLP", "Multi-Modal Logistics Park"],
  ["POL", "Petroleum, Oil and Lubricants"],
];
